Api vaccine registration
zinza-d2-training/minhdh-react pull request #24
Opened 2023-01-16 10:03 UTC by dohongminh25

## Summary

## Dependencies

–

## Testing

2023-01-17 02:21 UTC, hungnp194 requested changes

2023-01-17 02:21 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +  useVaccinationSitesQuery();
call nhưng ko để làm gì?

2023-01-17 02:21 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +  };
Ko dùng thì xóa đi

2023-01-17 02:21 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +  }, [data]);
Dùng react-query và refetch của react-query

2023-01-17 02:21 UTC, hungnp194 commented on src/pages/vaccineRegistrationPage/VaccineStep1.tsx
>    };
same

2023-01-17 02:21 UTC, hungnp194 commented on src/pages/vaccineRegistrationPage/VaccineStep3.tsx
> +
same

2023-01-17 02:25 UTC, dohongminh25 commented on src/pages/adminPage/AdminPlace.tsx
> +  useVaccinationSitesQuery();
e call để lấy ra tất cả vaccination sites ạ

2023-01-17 02:25 UTC, dohongminh25 commented on src/pages/adminPage/AdminPlace.tsx
> +  };
cái này để admin update sites ạ

2023-01-17 10:16 UTC, hungnp194 requested changes

2023-01-17 10:16 UTC, hungnp194 commented on src/pages/adminPage/hooks/useVaccinationSitesQuery.ts
>  };
Sao lại sửa thế này? Return useQuery để còn dùng những function như refetch, isLoading, ... mà nó cung cấp chứ?
Data ở component muốn lấy thế nào thì useMemo ra

2023-01-17 10:16 UTC, hungnp194 commented on src/pages/homePage/componentsHome/InjectionSite.tsx
same

2023-01-18 06:10 UTC, hungnp194 requested changes

2023-01-18 06:10 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +    useVaccinationSitesQuery().data || [];
```suggestion
const vaccinationSitesQuery = useVaccinationSitesQuery()
  const injectionSites = useMemo(() => {
     return vaccinationSitesQuery.data ?? []
  }, [vaccinationSitesQuery.data ])
```

2023-01-18 06:10 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +  const refetchData: any = useVaccinationSitesQuery().refetch();
```suggestion
```

2023-01-18 06:10 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +    refetchData();
```suggestion
    vaccinationSitesQuery.refetch()
```

2023-01-18 06:10 UTC, hungnp194 commented on src/pages/adminPage/AdminPlace.tsx
> +    useVaccinationSitesQuery().data || [];
Làm tương tự các chỗ khác

2023-01-18 08:24 UTC, hungnp194 approved these changes

2023-01-18 08:24 UTC, merged